site_name: PtilopsisL

theme:
  name: 'material'
  language: 'zh'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.def_list
  - mdx_truly_sane_lists
  - toc:
      permalink: true

extra_css:

nav:
  - 首页: README.md
